# -*- coding: utf-8 -*-
"""testing_your_own_code_practice_with_credit_card_transactions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11M3V_wZoflAj3EgtOUH-Ss4GTSoTkfz0

Organize your table into teams. Normally for something like this you organize into [red and blue teams](https://en.wikipedia.org/wiki/Red_team) but I guess we should probably do black and gold teams, huh?

### Business logic 

- You work for a credit card company
- You want to avoid fraudulent transactions.
- One way to avoid fraudulent transactions is to ensure that a customers name, number and address match the records your database
- So when the person goes to make a transaction online, if they give an address or name that does not match the number, you can reject the transaction.
- Write a function `is_ok` which returns `True` if the name, number and address from a transaction match the record in your database. And false otherwise.

Start off by finishing the function. Your code should fail the test until you fix it.
"""

def match(_database_record: dict, _transaction: dict) -> bool:
  if type(_database_record) != dict:
    raise Exception("Wrong input type")
  if type(_transaction) != dict:
    raise Exception("Wrong input type")

  if type(_transaction["name"]) != str:
    raise Exception("Wrong input type")  
  if type(_transaction["number"]) != str:
    raise Exception("Wrong input type")  
  if type(_transaction["address"]) != str:
    raise Exception("Wrong input type")

  if type(_transaction["name"]) == "":
    raise Exception("Name input is empty")  
  if type(_transaction["number"]) == "":
    raise Exception("Number input is empty")  
  if type(_transaction["address"]) == "":
    raise Exception("Address is empty")

  if (transaction["name"] in database_record["name"]) and (transaction["name"] != database_record["name"]):
    raise TypeError("It is the same name not in the same format")
  if (transaction["name"].lower() == database_record["name"].lower()) and (transaction["name"] != database_record["name"]):
    raise TypeError("Only capitalize the first letter of your names")

  period = "."
  comma = ","
  dash = "-"
  if period in (_transaction["name"]):
    raise Exception("Remove punctuation")
  if comma in (_transaction["name"]):
    raise Exception("Remove punctuation")
  if dash in (_transaction["name"]):
    raise Exception("Remove punctuation")

  if _database_record == _transaction:
    return True
  else:
    return False

database_record = {"name": "Grisha Brenden", "number": "12395", "address": "995 Regent Dr"}
transaction = {"name": "Grisha. Brenden", "number": "12395", "address": "995 Regent Dr"}

match(database_record,transaction)

"""Now write tests for your own function to check for edge cases. When will the business logic fail?"""

assert match(_database_record=database_record, _transaction=transaction)
assert type(match(_database_record=database_record, _transaction=transaction)) == bool

"""In a few minutes you will post your code on GitHub and invite the other team to try and find holes in it with their tests. Do you want to do anything to "harden" your code? Can you think of things the other team will miss? The team that finds the most issues with the other teams code (across the whole class) will get extra credit. Each issue is equal to one test.

Ok now post your code on GitHub. Copy the other teams code into  your notebook. (You can also use GitHub features to do this programmatically, which is better but beyond the scope of the class).  Then run your tests on their code to see if you find issues that they did not think of.

Count up how many issues you find with the other team's code. An issue is a test that reveals a flaw in the business logic. Basically, if you find a reasonable hole in the other team's logic using a test, that counts as an issue.
"""

